name = "ClusteringDifferences"
uuid = "a029d29b-0e57-4782-a64c-38d2809d16dd"
authors = ["Lars Sch√ºtz"]
version = "0.1.0"

[deps]
DifferencesBase = "f7c07657-0d0a-4d46-b086-01df223a7b4f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"

[compat]
DifferencesBase = "0.1.0, 0.2"
Distances = "0.8.2"
julia = "1.3"
